name: ci 
on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - run: pip install mkdocs mkdocs-terminal  # Install MkDocs explicitly

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-name origin
